apiVersion: v1
kind: Service
metadata:
  name: back-end-service
  namespace: {{ .Values.namespace }}
  labels:
    app: crud-go-react
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: crud-go-react
    tier: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
