apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: crud-go-react
    tier: frontend
  namespace: crud-app
spec:
  type: LoadBalancer
  selector:
    app: crud-go-react
    tier: frontend
  ports:
  - port: 80
    targetPort: 80